---
title: "AQP_test"
author: "Madelyn Willis"
date: "`r Sys.Date()`"
output: html_document
---

```{r Library Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#remove pound symbols below if not yet installed 
#install.packages("aqp") 
#install.packages("soilDB")
library(aqp)
library(soilDB)
#library(sharpshootR)
library(dendextend)
library(latticeExtra)
library(ggplot2)
library(RColorBrewer)
library(SoilTaxonomy)
library(dplyr)
library(janitor)
library(tidyr)
library(stringr)
library(cluster)
library(terra)
```



```{r Data Frame}

FPspatial <- terra::vect("../Data/Full Profile Data/Spatial/Perry_all_FP_samples_clean.shp")

# Load Perry data and wrangle
data_frame <- read.csv("../Data/Full Profile Data/Final_Perry_FP_data_2025.csv", header = TRUE, sep = ",")
data_frame <- data_frame %>%
  clean_names %>% 
  rename(id = sample_id_lab) %>% #rename to id
  rename(hzid = horizon) %>% #rename to hzid
  mutate(top = as.numeric(sub("-.*", "", to_depth_cm)),  # Extracts the top depth
    bottom = as.numeric(str_remove(sub(".*-", "", to_depth_cm), "\\+"))) # Extracts and removes "+" from bottom

 
# Define a mapping of texture abbreviations to their full names
texture_map <- c(
  "LS" = "loamy_sand",
  "SCL" = "sandy_clay_loam",
  "SL" = "sandy_loam",
  "L" = "loam",
  "CL" = "clay_loam",
  "S" = "sand",
  "C" = "clay",
  "SIL" = "silt_loam",
  "SI" = "silt",
  "SC" = "sandy_clay",
  "C " = "clay"
)


# Replace texture abbreviations with full names
data_frame <- data_frame %>%
  mutate(texture = recode(lab_texture_lpsa_preliminary, !!!texture_map)) %>%
  mutate( # Use regex to add a space between hue and value/chroma
    color_corrected = gsub("([A-Za-z]+)([0-9]+)", "\\1 \\2", matrix_color),
    # Split color into three parts: Hue, Value, and Chroma
    hue = sapply(strsplit(as.character(color_corrected), " "), function(x) x[1]),
    value_chroma = sapply(strsplit(as.character(color_corrected), " "), function(x) x[2]),
    value = sapply(strsplit(value_chroma, "/"), function(x) x[1]),
    chroma = sapply(strsplit(value_chroma, "/"), function(x) x[2]),
    color = munsell2rgb(the_hue = hue, the_value = value,  # Split the 'color' column into separate hue, value, and chroma components
    the_chroma = chroma, return_triplets=FALSE)) #return triplets is false bc otherwise it gives 3 columns with separate rgb
  
data_frame$rgb_values <- munsell2rgb(the_hue = data_frame$hue,
                                     the_value = as.numeric(data_frame$value),
                                     the_chroma = as.numeric(data_frame$chroma),
                                     return_triplets = TRUE)

# Split RGB values into separate columns
data_frame <- data_frame %>%
  mutate(red = rgb_values[, 1],
         green = rgb_values[, 2],
         blue = rgb_values[, 3])

# template data:
## 'data.frame':    30 obs. of  13 variables:
##  $ id         : chr  "colusa" "colusa" "colusa" "colusa" ...
##  $ name       : chr  "A" "ABt" "Bt1" "Bt2" ...
##  $ top        : int  0 3 8 30 0 9 0 4 13 0 ...
##  $ bottom     : int  3 8 30 42 9 34 4 13 40 6 ...
##  $ K          : num  0.3 0.2 0.1 0.1 0.2 0.3 0.2 0.6 0.8 0.4 ...
##  $ Mg         : num  25.7 23.7 23.2 44.3 21.9 18.9 12.1 12.1 17.7 16.4 ...
##  $ Ca         : num  9 5.6 1.9 0.3 4.4 4.5 1.4 7 4.4 24.1 ...
##  $ CEC_7      : num  23 21.4 23.7 43 18.8 27.5 23.7 18 20 31.1 ...
##  $ ex_Ca_to_Mg: num  0.35 0.23 0.08 0.01 0.2 0.2 0.58 0.51 0.25 1.47 ...
##  $ sand       : int  46 42 40 27 54 49 43 36 27 43 ...
##  $ silt       : int  33 31 28 18 20 18 55 49 45 42 ...
##  $ clay       : int  21 27 32 55 25 34 3 15 27 15 ...
##  $ CF         : num  0.12 0.27 0.27 0.16 0.55 0.84 0.5 0.75 0.67 0.02 ...
# optionally read about it with ?sp4
#we dont have CF yet....
# Create a mapping for horizon names to numerical codes
# Create a named vector for horizon codes
      horizon_mapping <- c(
        "Ap" = 1,
        "AB" = 2,
        "Bt1" = 3,
        "Bt2" = 3,
        "Ab" = 4,
        "Btb1" = 5,
        "Btb2" = 5,
        "Bt3" = 3,
        "Bt4" = 3,
        "AE" = 6,
        "BA" = 7,
        "BCg" = 8,
        "BE" = 9,
        "Bt" = 3,
        "Btv" = 10,
        "Bw" = 11,
        "Bwb" = 12,
        "C" = 13,
        "BC" = 14,
        "Ap1" = 1,
        "Ap2" = 1,
        "Eb1" = 15,
        "Eb2" = 15,
        "Eb3" = 15,
        "Btb" = 5,
        "Btv1" = 10,
        "Btv2" = 10,
        "^Ap" = 16,
        "^C1" = 17,
        "^C2" = 17,
        "Btg" = 18,
        "A/E" = 6,
        "E" = 19,
        "Btvg" = 20,
        "^C3" = 17,
        "E1" = 19,
        "E2" = 19,
        "E3" = 19,
        "^C" = 17,
        "2Bt" = 21
      )
hotcoded_data <- data_frame %>%
  mutate(hzid = as.factor(hzid)) %>%  # Convert hzid to a factor
  model.matrix(~ hzid - 1, .) %>%     # Create binary columns for each level of hzid
  as.data.frame()                     # Convert to a data frame
#merge with spatial data:
data_spat <- data_frame %>%
  left_join(FPspatial, by = c("point" = "Point_ID"), copy = TRUE) #%>%
  #mutate(point = as.character(point)) %>%
 # select(-geometry)
# # Combine the one-hot-encoded columns with the original data (if needed)
# data_frame_with_hotcoding <- bind_cols(data_frame, hotcoded_data)
#Apply the horizon mapping to create `horizon_code`
data_frame <- data_frame %>%
  mutate(hzid = ifelse(str_starts(hzid, "^"), str_remove(hzid, "\\^"), hzid),
         hzid = str_replace(hzid, "A/E", "AE"),
         hzid = ifelse(hzid == "", NA, hzid),
    depletions = ifelse(depletions == "Yes", 1, 0),
    htm = ifelse(htm == "Yes", 1, 0),
    first_letter = str_sub(hzid, 1, 1),  # Extract the first letter
    first_letter_code = case_when(
      first_letter == "A" ~ 1,  # Assign code 1 for horizons starting with "A"
      first_letter == "B" ~ 2,  # Assign code 2 for horizons starting with "B"
      first_letter == "C" ~ 3,  # Assign code 3 for horizons starting with "C"
      first_letter == "E" ~ 4,  # Assign code 4 for horizons starting with "E"
      TRUE ~ 0                  # Assign code 0 for anything else
    ),
    intermingle_body = ifelse(intermingle_body == "Yes", 1, 0),
    concentrations = ifelse(concentrations == "Yes", 1, 0),
    horizon_code = horizon_mapping[hzid] ) %>%
dplyr::select(point, id, hzid, top, bottom, texture, sand, silt, clay, color, red, green, blue, depletions, concentrations, first_letter_code, htm, intermingle_body) %>% #column selection
arrange(point, id, hzid, top, bottom, texture, clay, sand, silt, color) #order


# Create a SoilProfileCollection object:
aqp::depths(data_frame) <- point ~ top + bottom
#site(spc) <- data_frame[, c("id")]  # Assign profile-level data
#horizons(spc) <- data_frame         # Assign horizon-level data 


```


```{r cluster pedons}

#hotcoded_columns <- grep("^hzid", colnames(data_frame_with_hotcoding), value = TRUE)
# Compute the dissimilarity matrix using RGB values
dissimilarity_matrix <- NCSP(data_frame,
                             vars = c("red", "green", "blue","top","bottom","depletions", "concentrations", "first_letter_code", "htm", "intermingle_body" ), # Use RGB as numeric
                             maxDepth = 150,
                             k = 0.01)

# Print the results
# print(dissimilarity_matrix)
# dissimilarity_matrix <- NCSP(data_frame,
#                                         vars = c("color"),
#                                         maxDepth = 150,  
#                                         k = 0.01) 



# 
# hc <- hclust(as.dist(dissimilarity_matrix), method = "ward.D2")
# 
# num_clusters <- 6  # You can change this to the number of clusters you want
# clusters <- cutree(hc, k = num_clusters)
# 
# # Add clusters to the SPC site-level data
# site(data_frame)$cluster <- clusters
# 
# # Color the dendrogram by cluster
# dend <- as.dendrogram(hc)
# dend <- color_branches(dend, k = num_clusters)
# plot(dend, main = "Dendrogram of Pedons (Colored by Cluster)")
# 
# 

# site attributes: 
# D.s <- compareSites(data_frame, vars = c("hzid"))
# D <- Reduce(`+`, list(dissimilarity_matrix * 1)) / 1

diana <- diana(dissimilarity_matrix)

par(mar = c(1,0,3,1))
plotProfileDendrogram(data_frame, diana, label = "point",  width=.5, color = "color", cex.name=0.65, scaling.factor = 0.5, id.style = 'top', cex.id = .8, dend.color = 2)

grp <- cutree(diana, k = 12)

df <- data.frame(
  id = unique(data_frame$point),
  cluster = grp)

# Create sf object from data_frame

df_spatial <- merged_df_clean %>%
  left_join(df, by = c("point" = "id")) %>%
  mutate(cluster = as.factor(cluster)) %>%
  sf::st_as_sf(coords = c("lon", "lat"), crs = 3857)

df_spatial$cluster <- as.factor(df_spatial$cluster)







plot(df_spatial["cluster"], 
     col = cluster_colors[as.numeric(df_spatial$cluster)], 
     main = "Clustered Pedons", 
     pch = 19, 
     cex = 1.5, 
     axes = TRUE)

tmap_mode("view")

df_spatialt<-df_spatial %>%
  st_transform(4326)

leaflet(df_spatialt) %>%
  addProviderTiles(providers$Esri.WorldTopoMap) %>%
  addCircleMarkers(
    color = ~cluster_colors[as.numeric(cluster)],
    label = ~paste("Point:", point),
    radius = 5,
    fillOpacity = 0.7
  )



```
```{r}
library(dplyr)
library(sf)
library(concaveman) # for concave hulls
library(ggplot2)
library(purrr)


# Group by cluster and create concave polygons
# Split the sf object into a list of data frames by cluster
cluster_list <- df_spatial %>%
  group_by(cluster) %>%
  group_split()

# Apply concaveman to each cluster and keep cluster ID
cluster_polygons <- map_dfr(cluster_list, function(cluster_sf) {
  concave_poly <- concaveman(cluster_sf)
  cluster_id <- unique(cluster_sf$cluster)
  concave_poly$cluster <- cluster_id
  concave_poly
})
# Ensure both are in the same CRS (WGS84)
df_spatialt <- df_spatial %>% st_transform(4326)
# Ensure polygons are in WGS84 for leaflet
cluster_polygons_t <- cluster_polygons %>% st_transform(4326)

# Assign colors to each polygon row (use consistent coloring)
cluster_polygons_t$color <- cluster_colors[seq_len(nrow(cluster_polygons_t))]

# Create zone labels in advance
cluster_polygons_t$label <- paste("Zone", seq_len(nrow(cluster_polygons_t)))
# Drop Z and M dimensions from geometry
cluster_polygons_t <- st_zm(cluster_polygons_t, drop = TRUE, what = "ZM")

# Now plot
leaflet(cluster_polygons_t) %>%
  addProviderTiles(providers$Esri.WorldTopoMap) %>%
  addPolygons(
    fillColor = ~color,
    fillOpacity = 0.5,
    color = "black",
    weight = 1,
    label = ~label)



```
```{r}
library(dplyr)
library(randomForest)  # or ranger
library(caret)         # for train/test split

# 1. Prepare data

predictors <- df_spatial %>%
  st_drop_geometry() %>%
  dplyr::select(hzid, matrix_color, cluster, depletions, concentrations, htm, top, bottom) %>%
  mutate(cluster = as.factor(cluster))


# 2. Train-test split (80/20)
set.seed(123)
train_index <- createDataPartition(predictors$cluster, p = 0.8, list = FALSE)
train_data <- predictors[train_index, ]
test_data <- predictors[-train_index, ]

# 3. Fit Random Forest model
rf_model <- randomForest(cluster ~ ., data = train_data, ntree = 500, importance = TRUE)

# 4. Evaluate on test set
pred <- predict(rf_model, newdata = test_data)
confusion <- caret::confusionMatrix(pred, test_data$cluster)
print(confusion)

# 5. Variable importance plot
varImpPlot(rf_model)

library(dplyr)
library(sf)
library(tmap)

# Add predicted clusters to test_data
test_data <- test_data %>%
  mutate(pred_cluster = pred)

# Join test_data predictions back to spatial data by unique ID (hzid)
predicted_sf <- df_spatial %>%
  filter(hzid %in% test_data$hzid) %>%
  left_join(test_data %>% select(hzid, pred_cluster), by = "hzid")

# Plot predicted clusters
tmap_mode("plot")  # or "view" for interactive

tm_shape(predicted_sf) +
  tm_dots(col = "pred_cluster", palette = "Set3", 
          title = "Predicted Cluster", size = 0.7) +
  tm_layout(legend.outside = TRUE)


```



```{r}
library(dplyr)
library(sf)
library(caret)
library(randomForest)
library(tmap)

# 1. Prepare data, keep 'point' for joining but exclude from predictors
predictors <- df_spatial %>%
  st_drop_geometry() %>%
  dplyr::select(point, hzid, matrix_color, cluster, depletions, concentrations, htm, top, bottom) %>%
  mutate(cluster = as.factor(cluster))

# 2. Train-test split (80/20) using 'point' as identifier
set.seed(123)
train_index <- createDataPartition(predictors$cluster, p = 0.8, list = FALSE)
train_data <- predictors[train_index, ]
test_data <- predictors[-train_index, ]

# 3. Fit Random Forest model excluding 'point' as predictor
rf_model <- randomForest(cluster ~ . - point, data = train_data, ntree = 500, importance = TRUE)

# 4. Predict on test set and add predictions to test_data
pred <- predict(rf_model, newdata = test_data)
test_data <- test_data %>%
  mutate(pred_cluster = pred)

# 5. Join predictions back to spatial data by 'point'
predicted_sf <- df_spatial %>%
  filter(point %in% test_data$point) %>%
  left_join(test_data %>% 
              dplyr::select(point, pred_cluster), by = "point")

# 6. Plot predicted clusters using tmap
library(tmap)
tmap_mode("plot")
predicted_sf <- predicted_sf %>%
  dplyr::select(-rgb_values)  # Remove RGB values if not needed))
tm_shape(predicted_sf) +
  tm_dots(col = "pred_cluster", palette = "Set3", size = 0.7, title = "Predicted Cluster")


# Optional: print confusion matrix and variable importance
confusion <- caret::confusionMatrix(pred, test_data$cluster)
print(confusion)
varImpPlot(rf_model)

```
```{r}
library(raster)
library(randomForest)
library(dplyr)
library(sf)
library(tmap)

# 1. Load or prepare raster layers for all predictors (must match predictors used in model)
# Example: matrix_color_raster, depletions_raster, concentrations_raster, htm_raster, top_raster, bottom_raster

# Stack rasters
predictor_stack <- stack()

names(predictor_stack) <- c("matrix_color", "depletions", "concentrations", "htm", "top", "bottom")

# 2. Convert raster stack to data frame for prediction
predict_df <- as.data.frame(predictor_stack, xy = TRUE, na.rm = FALSE)

# 3. Make sure data types match model training (e.g., factor or numeric)
# Convert matrix_color to factor if needed:
predict_df$matrix_color <- as.factor(predict_df$matrix_color)

# 4. Predict clusters for all pixels
predict_df$pred_cluster <- predict(rf_model, newdata = predict_df)

# 5. Convert prediction back to raster
# Create empty raster for output
cluster_raster <- raster(predictor_stack[[1]])
# Assign predicted clusters, matching by cell index
cluster_raster[] <- as.numeric(as.factor(predict_df$pred_cluster))

# 6. Plot
plot(cluster_raster, col = rainbow(length(unique(predict_df$pred_cluster))),
     main = "Predicted Management Zones (Clusters)")

```



```{r Fetch Soil Series}
# Fetch OSD data for soil series in the southeastern U.S. IDK even if this is how this works bruh
perry_soil_series <- c("boswell", "faceville", "grady", "lucy","greenville","henderson", #based on SSURGO data
                       "lakeland", "lynchburg","norfolk","oktibbeha","orangeburg","red bay","sumter","susquehanna","vaucluse","dothan","americus","hazelhurst","clarendon")
osd_data <- fetchOSD(perry_soil_series, colorState = "moist")

```

```{r plot OSDs}

plotOSDs <- plotSPC(osd_data, name.style = 'center-center', max.depth = 150) ; title('OSD around Perry Ga')

```
```{r}
sorted_order <- order(site(data_frame)$point)

# Rebuild the SoilProfileCollection with the new profile order
data_frame <- data_frame[sorted_order, ]

plotSPC(data_frame,
        name = "hzid",
        label = "point",
        name.style = 'center-center',
        color = "color") ; title('All profiles in Perry')

subset_pedons <- subset(data_frame, point %in% c("80","78","57"))

plotSPC(subset_pedons,
        name = "hzid",
        label = "point",
        name.style = 'center-center',
        color = "color") ; title('Points 57, 78, 80')




subset_pedonse <- subset(data_frame, point %in% c("2"))

plotSPC(subset_pedonse,
        name = "hzid",
        label = "Point",
        name.style = 'center-center',
        color = "color") ; title('Point 2')

soil_series_albany <- fetchOSD(soils = c("albany"))
plot(soil_series_albany, name.style = 'center-center', max.depth = 150) ; title('Albany')

soil_series_bonneau <- fetchOSD(soils = c("bonneau"))
plot(soil_series_bonneau, name.style = 'center-center', max.depth = 150) ; title('Bonneau')

soil_series_greenville <- fetchOSD(soils = c("greenville"))
plot(soil_series_greenville, name.style = 'center-center', max.depth = 150) ; title('Greenville')
```

```{r Plot clusters}
# Subset specific IDs
subset_pedons1 <- subset(data_frame, point %in% c("29","30","40"))

# Plot the subset
plot(subset_pedons1, 
     name = "point",  # Label with texture
     label = "color")      # Label profiles with ID

# Subset specific IDs
subset_pedons2 <- subset(data_frame, point %in% c("68","69","61","62","63"))

# Plot the subset
plot(subset_pedons2, 
     name = "point",  # Label with texture
     label = "color")      # Label profiles with ID



# Step 1: Subset your pedons (e.g., "P1" and "44")
subset_pedons3 <- subset(data_frame, id %in% c("44", "34","P4","23"))

# Step 2: Fetch the "Grady" soil series data
soil_series_grady <- fetchOSD(soils = c("Grady"))

# Step 3: Create an empty plot and initialize
#plot(subset_pedons3, 
#     name = "point", 
#     label = "id", 
#     main = "Pedons P1 & 44 vs Grady Soil Series")

# Now, add the "Grady" soil series to the plot
plot(soil_series_grady)
```


```{r Soil Similarity func.}
# Similarity function based on Euclidean distance
calculate_similarity <- function(pedon, series_horizon) {
  sqrt(
    (pedon$sand - series_horizon$sand)^2 +
    (pedon$silt - series_horizon$silt)^2 +
    (pedon$clay - series_horizon$clay)^2)}


```



```{r Soil Series Match}
# Initialize list to store matches
matches <- list()

# Loop through each pedon in your data
for (i in unique(data_frame$id)) {
  # Subset data for the current pedon
  pedon <- data_frame %>% filter(id == i)
  
  # Calculate similarity for each soil series
  similarities <- sapply(osd_data$horizons, function(series_horizon) {
    mean(sapply(1:nrow(pedon), function(j) {
      calculate_similarity(pedon[j, ], series_horizon)
    }), na.rm = TRUE)
  })
  
  # Find the best match
  best_match <- names(which.min(similarities))
  matches[[i]] <- best_match
}

# Create a data frame of matches
matched_series <- data.frame(
  id = names(matches),
  best_match = unlist(matches)
)

print(matched_series)

```

```{r Network}
# get basic OSD data for queried series and siblings
s <- siblings('orangeburg', component.data = TRUE)
s.list <- unique(c(s$sib$series[1], s$sib$sibling))
h <- fetchOSD(s.list)

# plot dendrogram + profiles
SoilTaxonomyDendrogram(h, y.offset = 0.4, width = 0.3, name.style = 'center-center', depth.axis = list(line = -3))

```


```{r test}
s2 <- siblings('orangeburg', component.data = TRUE)
```


```{r save profiles}
for (profile_point in unique(site(data_frame)$point)) {
  
  # Subset point
  profile_subset <- data_frame[site(data_frame)$point == profile_point, ]
  
  output_file <- file.path("../output/profile_plots", paste0("Profile_Point_", profile_point, ".png"))
  
  # Save plot
  png(filename = output_file, width = 1200, height = 800)
  plotSPC(profile_subset,
          name = "hzid",
          label = "point",
          name.style = 'center-center',
          color = "color",
          cex.names = 1.5, 
          cex.id = 1.5)    
  title(paste("Profile for Point:", profile_point))
  dev.off()
}

cat("done:", output_folder)
```



