---
title: "Perry_analysis"
author: "Madelyn Willis"
date: "`r Sys.Date()`"
output: html_document
---

##Unloading Necessary Packages
```{r Packages, include=FALSE}
#chunk options
knitr::opts_chunk$set(echo = TRUE)

    #libraries
#library(reticulate)
#library(rgee)
#ee_Authenticate()
#ee_Initialize()
library(sf)
library(tidyverse)
library(raster)
library(terra)
library(ggplot2)
library(viridis)
library(corrr)
library(rstac)
library(ggcorrplot)
library(GGally)
library(randomForest)
library(sp)
library(gstat)
library(automap)
library(tmap)
library(parallel)
library(caret)
library(factoextra)
library(corrplot)
library(tidymodels)
library(glmnet)
library(vip)
library(tidyterra)
```

##Pulling Data & Imagery


```{r ALL data pull, message = FALSE}
#Grabbing Sample ID's
soil_points <- st_read("../Local Data- DO NOT PUSH/Perry_all points_17N/all_samples_points_perry_2.shp") %>%
  pivot_longer(cols = c("CID","SPID"), names_to ="type", values_to = "ID")
  

#CSV of AESL data:
soil_all <- read.csv("../Local Data- DO NOT PUSH/Perry_all_samples_all.csv")

# Merge points + sample data:
soil_points <- merge(soil_points, soil_all, by = "ID") #CID and SPID


write_csv(soil_points, "../Local Data- DO NOT PUSH/soil_points.csv")

# Load the USGS 1m DEM (acts as the template)
USGS_DEM <- rast("../Local Data- DO NOT PUSH/DEM rasters/output_USGS1m.tif")

# border:
border <- vect("../Local Data- DO NOT PUSH/Border/border_17N.shp") #points 124 and 136 are NOT within bounds. That's why we are using different border
border_ext <-ext(border)

#topo stack:
clipped_stack <- terra::rast("../Local Data- DO NOT PUSH/clipped_stack.tif") 

#surface reflectance run through PCA:
PCA_SR <- terra::rast("../Local Data- DO NOT PUSH/PCA_SR.tif") 

#NDVI:
NDVI <- terra::rast("../Local Data- DO NOT PUSH/NDVI.tif") 

```





```{r wrangling}


#stack all
covariates <- c(PCA_SR, clipped_stack, NDVI)

#make names valid
names(covariates) <- make.names(names(covariates))

#sort by SINGLE POINT DATA
soil_points_singlepoint <- filter(soil_points, type == "SPID")

#sort by COMPOSITE DATA
soil_points_composite <- filter(soil_points, type == "CID")

# vect the sample data
soil_points_vect_SP <- vect(soil_points_singlepoint)
soil_points_vect_C <- vect(soil_points_composite)


# Extract raster values at soil sample points
soil_points_SPID <- terra::extract(covariates, soil_points_vect_SP, bind = T,xy = T)
soil_points_CID <- terra::extract(covariates, soil_points_vect_C, bind = T,xy = T)


#convert to df
soils_df_SP <- as.data.frame(soil_points_SPID)
soils_df_C <- as.data.frame(soil_points_CID)

# Select only the soil property columns
soil_df_cols_SP <- soils_df_SP[, c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn')]
soil_df_cols_C <- soils_df_C[, c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn')]


#exclude non essential data:
soils_df_wrang_SP <- soils_df_SP[ ,-(1:9)]
soils_df_wrang_C <- soils_df_C[ ,-(1:9)]

```


##RF
###Correlation Matrix
```{r CM }
# Compute correlation matrix
cor_matrix_SP <- cor(soils_df_wrang_SP, use = "pairwise.complete.obs", method = "spearman")
cor_matrix_C <- cor(soils_df_wrang_C, use = "pairwise.complete.obs", method = "spearman")

```

```{r plotting CM }
#formatting:
ggcorrplot(cor_matrix_SP, type = "lower", 
           lab = TRUE, show.legend = TRUE, 
           tl.cex = 4, # Adjust text size
           lab_size = 2, # Adjust correlation label size
           tl.srt = 45) # Rotate axis labels

ggcorrplot(cor_matrix_SP, type = "lower", 
           lab = TRUE, show.legend = TRUE, 
           tl.cex = 4, # Adjust text size
           lab_size = 2, # Adjust correlation label size
           tl.srt = 45,           
           hc.order = TRUE, # Cluster similar variables together
           insig = "blank", # Hide insignificant correlations
           p.mat = cor_pmat(soils_df_wrang_SP)
           ) # Rotate axis labels


# col name of soil properties
soil_vars <- colnames(soil_df_cols_SP)
# topo name list
topo_vars <- setdiff(colnames(soils_df_wrang_SP), soil_vars)

# Compute correlation matrix only between soil properties and topo rasters
cor_matrix_soil_topo_SP <- cor(soils_df_wrang_SP[, soil_vars], soils_df_wrang_SP[, topo_vars], 
                            use = "pairwise.complete.obs", method = "spearman")

# Visualize
ggcorrplot(cor_matrix_soil_topo_SP, lab = TRUE, show.legend = TRUE, 
           tl.cex = 5, lab_size = 2, tl.srt = 45, method = "circle")

#save png of corr matrix
#ggsave("../Mapping/Output/Correlation_Matrix_all.png")

```
###PCA
```{r PCA}

PCA_covar <- terra::princomp(covariates) #PCA of covariates

PCA_data <- stats::prcomp(soils_df_wrang_SP, scale = T) #PCA of soil data with just sp

PCA_var <- get_pca_var(PCA_data)

fviz_pca_var(PCA_covar, col.var = "cos2")

fviz_contrib(PCA_covar, choice = "var", axes = 1:3)
#?
PCA_<-PCA_covar$sdev^2
write.csv(PCA_,file="../Local Data- DO NOT PUSH/PCA_covar.csv")

```


```{r train test + dist graphs}
set.seed(626)

list_train <- list()

list_graph <- list()

list_test <- list()

for (i in 1:9) {
  nutrient<- colnames(soils_df_wrang_SP[i])
  set_split <- initial_split(soils_df_wrang_SP,prop = 0.8, strata = nutrient)
  set_train <- training(set_split)
  set_test <- testing(set_split) 
  list_graph[[i]] <- ggplot() +
  geom_density(data = set_train, 
               aes(x = .data[[nutrient]]),
               color = "red") +
  geom_density(data = set_test, 
               aes(x = .data[[nutrient]]),
               color = "blue")
  list_train[[i]] <- set_train
  list_test[[i]] <- set_test
}

names<-colnames(soils_df_wrang_SP[1:9])

names_train<-paste0(names,"_train")

names_test<-paste0(names,"_test")

names(list_train)<-names_train

names(list_test)<-names_test

list2env(c(list_train,list_test) ,.GlobalEnv)


```

###RF
```{r Random Forest method}
#seed:
set.seed(626)

# partition <- function(df, p, nutrient){
#   
#     set_split <- initial_split(df,prop = p, strata = nutrient)
#     set_train <- training(set_split)
#     
#     set_test <- testing(set_split)
#     ggplot() +
#   geom_density(data = set_train, 
#                aes(x = nutrient),
#                color = "red") +
#   geom_density(data = set_test, 
#                aes(x = nutrient),
#                color = "blue")} 

#set train control:
trainControl <- trainControl(method = "cv", number = 5)


# # #LBC: NOT necessary as LBC is NOT spatially correlated
# LBC.1_df <-  soils_df_wrang_SP %>%
#   dplyr::select(-c('LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))
# 
# LBC.1_index_train <- caret::createDataPartition(LBC.1_df$LBC.1, p = .8, list = F)
# 
# LBC.1_df_train <- LBC.1_df[LBC.1_index_train,]
# LBC.1_df_test <- LBC.1_df[-LBC.1_index_train,]
# 
# LBC.1_rf <- train(LBC.1 ~ ., data = LBC.1_df_train, method = "rf", trControl = trainControl)
# 
# print(LBC.1_rf)
# 
# predictors(LBC.1_rf)
# 
# LBC.1_predict <- terra::predict(covariates, LBC.1_rf, na.rm=TRUE)
# 
# plot(LBC.1_predict, main = "LBC RF")


#LBC stratified: BETTER
LBC.1_df_strata <-  LBC.1_train %>%
  dplyr::select(-c('LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))

LBC.1_rf_strata <- train(LBC.1 ~ ., data = LBC.1_df_strata, method = "rf", trControl = trainControl)

print(LBC.1_rf_strata)

predictors(LBC.1_rf_strata)

LBC.1_predict_strata <- terra::predict(covariates, LBC.1_rf_strata, na.rm=TRUE)

plot(LBC.1_predict_strata, main = "LBC RF Stratified")

terra::writeRaster(LBC.1_predict_strata, "../Local Data- DO NOT PUSH/rf nutrient rasters/LBC.1_predict_strata.tif", overwrite = TRUE)

#pH

pH.2_df <- soils_df_wrang_SP %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))

pH.2_index_train <- caret::createDataPartition(pH.2_df$pH.2, p = .8, list = F)

pH.2_df_train <- pH.2_df[pH.2_index_train,]
pH.2_df_test <- pH.2_df[-pH.2_index_train,]



pH.2_rf <- train(pH.2 ~ ., data = pH.2_df_train, method = "rf", trControl = trainControl)

print(pH.2_rf)

predictors(pH.2_rf)


pH.2_predict <- terra::predict(covariates, pH.2_rf, na.rm=TRUE)

plot(pH.2_predict, main = "pH RF")

terra::writeRaster(pH.2_predict, "../Local Data- DO NOT PUSH/rf nutrient rasters/pH.2_predict.tif", overwrite = TRUE)

# # #pH stratified:
# pH.2_df_strata <-  pH.2_train %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'Ca', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))
# 
# pH.2_rf_strata <- train(pH.2 ~ ., data = pH.2_df_strata, method = "rf", trControl = trainControl)
# 
# print(pH.2_rf_strata)
# 
# predictors(pH.2_rf_strata)
# 
# pH.2_predict_strata <- terra::predict(covariates, pH.2_rf_strata, na.rm=TRUE)
# 
# plot(pH.2_predict_strata, main = "pH RF Stratified")


#Ca:
Ca_df <- soils_df_wrang_SP %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))

Ca_index_train <- caret::createDataPartition(Ca_df$Ca, p = .8, list = F)

Ca_df_train <- Ca_df[Ca_index_train,]
Ca_df_test <- Ca_df[-Ca_index_train,]


Ca_rf <- train(Ca ~ ., data = Ca_df_train, method = "rf", trControl = trainControl)

print(Ca_rf)

predictors(Ca_rf)


Ca_predict <- terra::predict(covariates, Ca_rf, na.rm=TRUE)

plot(Ca_predict, main = "Ca RF")

terra::writeRaster(Ca_predict, "../Local Data- DO NOT PUSH/rf nutrient rasters/Ca_predict.tif", overwrite = TRUE)

# #Ca stratified:
# Ca_df_strata <-  Ca_train %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'K', 'Mg', 'Mn', 'P', 'Zn','x','y'))
# 
# Ca_rf_strata <- train(Ca ~ ., data = Ca_df_strata, method = "rf", trControl = trainControl)
# 
# print(Ca_rf_strata)
# 
# predictors(Ca_rf_strata)
# 
# Ca_predict_strata <- terra::predict(covariates, Ca_rf_strata, na.rm=TRUE)
# 
# plot(Ca_predict_strata, main = "Ca RF Stratified")

#K:

K_df <- soils_df_wrang_SP %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'Mg', 'Mn', 'P', 'Zn','x','y'))

K_index_train <- caret::createDataPartition(K_df$K, p = .8, list = F)

K_df_train <- K_df[K_index_train,]
K_df_test <- K_df[-K_index_train,]


K_rf <- train(K ~ ., data = K_df_train, method = "rf", trControl = trainControl)

print(K_rf)

predictors(K_rf)

K_predict <- terra::predict(covariates, K_rf, na.rm=TRUE)

plot(K_predict, main = "K RF")

terra::writeRaster(K_predict, "../Local Data- DO NOT PUSH/rf nutrient rasters/K_predict.tif", overwrite = TRUE)


# #K stratified:
# K_df_strata <-  K_train %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'Mg', 'Mn', 'P', 'Zn','x','y'))
# 
# K_rf_strata <- train(K ~ ., data = K_df_strata, method = "rf", trControl = trainControl)
# 
# print(K_rf_strata)
# 
# predictors(K_rf_strata)
# 
# K_predict_strata <- terra::predict(covariates, K_rf_strata, na.rm=TRUE)
# 
# plot(K_predict_strata, main = "K RF Stratified")

#Mg:

Mg_df <- soils_df_wrang_SP %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mn', 'P', 'Zn','x','y'))

Mg_index_train <- caret::createDataPartition(Mg_df$Mg, p = .8, list = F)

Mg_df_train <- Mg_df[Mg_index_train,]
Mg_df_test <- Mg_df[-Mg_index_train,]


Mg_rf <- train(Mg ~ ., data = Mg_df_train, method = "rf", trControl = trainControl)

print(Mg_rf)

predictors(Mg_rf)

Mg_predict <- terra::predict(covariates, Mg_rf, na.rm=TRUE)

plot(Mg_predict, main = "Mg RF")

terra::writeRaster(Mg_predict, "../Local Data- DO NOT PUSH/rf nutrient rasters/Mg_predict.tif", overwrite = TRUE)


#Mg stratified:

# Mg_df_strata <-  Mn_train %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mn', 'P', 'Zn','x','y'))
# 
# Mg_rf_strata <- train(Mg ~ ., data = Mg_df_strata, method = "rf", trControl = trainControl)
# 
# print(Mg_rf_strata)
# 
# predictors(Mg_rf_strata)
# 
# Mg_predict_strata <- terra::predict(covariates, Mg_rf_strata, na.rm=TRUE)
# 
# plot(Mg_predict_strata, main = "Mg RF Stratified")

# #Mn:

Mn_df <- soils_df_wrang_SP %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'P', 'Zn','x','y'))

Mn_index_train <- caret::createDataPartition(Mn_df$Mn, p = .8, list = F)

Mn_df_train <- Mn_df[Mn_index_train,]
Mn_df_test <- Mn_df[-Mn_index_train,]


Mn_rf <- train(Mn ~ ., data = Mn_df_train, method = "rf", trControl = trainControl)

print(Mn_rf)

predictors(Mn_rf)

Mn_predict <- terra::predict(covariates, Mn_rf, na.rm=TRUE)

plot(Mn_predict, main = "Mn RF")

terra::writeRaster(Mn_predict, "../Local Data- DO NOT PUSH/rf nutrient rasters/Mn_predict.tif", overwrite = TRUE)


# #Mn stratified:
# Mn_df_strata <-  Mn_train %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'P', 'Zn','x','y'))
# 
# Mn_rf_strata <- train(Mn ~ ., data = Mn_df_strata, method = "rf", trControl = trainControl)
# 
# print(Mn_rf_strata)
# 
# predictors(Mn_rf_strata)
# 
# Mn_predict_strata <- terra::predict(covariates, Mn_rf_strata, na.rm=TRUE)
# 
# plot(Mn_predict_strata, main = "Mn RF Stratified")


# #P:
# 
# P_df <- soils_df_wrang_SP %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'Zn','x','y'))
# 
# P_index_train <- caret::createDataPartition(P_df$P, p = .8, list = F)
# 
# P_df_train <- P_df[P_index_train,]
# P_df_test <- P_df[-P_index_train,]
# 
# 
# P_rf <- train(P ~ ., data = P_df_train, method = "rf", trControl = trainControl)
# 
# print(P_rf)
# 
# predictors(P_rf)
# 
# P_predict <- terra::predict(covariates, P_rf, na.rm=TRUE)
# 
# plot(P_predict, main = "P RF")


#P stratified: BETTER
P_df_strata <-  P_train %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'Zn','x','y'))

P_rf_strata <- train(P ~ ., data = P_df_strata, method = "rf", trControl = trainControl)

print(P_rf_strata)

predictors(P_rf_strata)

P_predict_strata <- terra::predict(covariates, P_rf_strata, na.rm=TRUE)

plot(P_predict_strata, main = "P RF Stratified")

terra::writeRaster(P_predict_strata, "../Local Data- DO NOT PUSH/rf nutrient rasters/P_predict.tif", overwrite = TRUE)


  # #p CID adjusted with points
  # P_predict_adjusted_C <- P_predict_strata
  # 
  # soil_points_sf_CID <- st_as_sf(soil_points_CID, coords = c("x", "y"), crs = st_crs(covariates))
  # 
  # coords <- st_coordinates(soil_points_sf_CID)
  # P_predict_adjusted_C[terra::cellFromXY(P_predict_strata, coords)] <- soil_points_sf_CID$P
  # 
  # plot(P_predict_adjusted_C)
  
  
    #p SPID adjusted with points
  P_predict_adjusted_SP <- P_predict_strata
  
  soil_points_sf_SPID <- st_as_sf(soil_points_SPID, coords = c("x", "y"), crs = st_crs(covariates))
  
  coords <- st_coordinates(soil_points_sf_SPID)
  P_predict_adjusted_SP[terra::cellFromXY(P_predict_strata, coords)] <- soil_points_sf_SPID$P
  
  plot(P_predict_adjusted_SP)

#Zn:
# 
# Zn_df <- soils_df_wrang_SP %>%
#   dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P','x','y'))
# 
# Zn_index_train <- caret::createDataPartition(Zn_df$Zn, p = .8, list = F)
# 
# Zn_df_train <- Zn_df[Zn_index_train,]
# Zn_df_test <- Zn_df[-Zn_index_train,]
# 
# 
# Zn_rf <- train(Zn ~ ., data = Zn_df_train, method = "rf", trControl = trainControl)
# 
# print(Zn_rf)
# 
# predictors(Zn_rf)
# 
# Zn_predict <- terra::predict(covariates, Zn_rf, na.rm=TRUE)
# 
# plot(Zn_predict, main = "Zn RF")

#Zn stratified: BETTER
Zn_df_strata <-  Zn_train %>%
  dplyr::select(-c('LBC.1', 'LBCeq', 'pH.2', 'Ca', 'K', 'Mg', 'Mn', 'P','x','y'))

Zn_rf_strata <- train(Zn ~ ., data = Zn_df_strata, method = "rf", trControl = trainControl)

print(Zn_rf_strata)

predictors(Zn_rf_strata)

Zn_predict_strata <- terra::predict(covariates, Zn_rf_strata, na.rm=TRUE)

plot(Zn_predict_strata, main = "Zn RF Stratified")

terra::writeRaster(Zn_predict_strata, "../Local Data- DO NOT PUSH/rf nutrient rasters/Zn_predict.tif", overwrite = TRUE)



```
```{r distributions of train and test, eval = FALSE}

plotdist <- function(train, nutrient_train, test, nutrient_test) {
  ggplot() +
  geom_density(data = train, 
               aes(x = nutrient_train),
               color = "red") +
  geom_density(data = test, 
               aes(x = nutrient_test),
               color = "blue") +
    labs(title = "train vs test data, not stratified")
}

# stack_train <- c(LBC_df_train, pH_df_train, Ca_df_train, K_df_train, Mg_df_train, Mn_df_train, Zn_df_train)
# stack_test<- c(LBC_df_test, pH_df_test, Ca_df_test, K_df_test, Mg_df_test, Mn_df_test, Zn_df_test)
# 
# for (i in length(stack_train))
#   {plotdist([i], i$[i], [i], i$[i])}


#LBC
LBC_og_dist <- plotdist(LBC.1_df_train , LBC.1_df_train$LBC.1, LBC.1_df_test , LBC.1_df_test$LBC.1) #dissimilar
#pH
pH_og_dist <-plotdist(pH.2_df_train, pH.2_df_train$pH.2, pH.2_df_test, pH.2_df_test$pH.2)

#Ca
Cz_og_dist <-plotdist(Ca_df_train, Ca_df_train$Ca, Ca_df_test, Ca_df_test$Ca)

#K
K_og_dist <-plotdist(K_df_train, K_df_train$K, K_df_test, K_df_test$K)

#Mg
Mg_og_dist <-plotdist(Mg_df_train, Mg_df_train$Mg, Mg_df_test, Mg_df_test$Mg)

#Mn
Mn_og_dist <-plotdist(Mn_df_train, Mn_df_train$Mn, Mn_df_test, Mn_df_test$Mn) #dissimilar

#P
P_og_dist <-plotdist(P_df_train, P_df_train$P, P_df_test, P_df_test$P)

#Zn
Zn_og_dist <-plotdist(Zn_df_train, Zn_df_train$Zn, Zn_df_test, Zn_df_test$Zn)


# #plots: example is LBC:
# LBC_og_dist
# list_graph[[1]]

```

```{r finding out if unstrat or strat is better, eval = FALSE}
#function of similarity
compare_train_test_similarity <- function(train, test) {
  density_train <- density(train, na.rm = TRUE)
  density_test <- density(test, na.rm = TRUE)

  common_x <- seq(min(c(density_train$x, density_test$x)),
                  max(c(density_train$x, density_test$x)),
                  length.out = 100)

  y_train <- approx(density_train$x, density_train$y, xout = common_x, rule = 2)$y
  y_test <- approx(density_test$x, density_test$y, xout = common_x, rule = 2)$y

  mad_value <- mean(abs(y_train - y_test), na.rm = TRUE)
  correlation <- cor(y_train, y_test, use = "complete.obs")

  return(list(MAD = mad_value, Correlation = correlation))
}

similarity <- function(train, test, nutrient){
  # Original
  similarity_original <- compare_train_test_similarity(train[[nutrient]], test[[nutrient]])
  
  # Stratified
  similarity_list <- compare_train_test_similarity(
    list_train[[paste0(nutrient, "_train")]][[nutrient]], 
    list_test[[paste0(nutrient, "_test")]][[nutrient]]
  )
  
  # Print results
  print(paste0("Results for ", nutrient, ":"))
  print(similarity_original)
  print(similarity_list)
  
  if (similarity_original$MAD < similarity_list$MAD & 
      similarity_original$Correlation > similarity_list$Correlation) {
    message(paste0(nutrient, ": The original test and train distributions are more similar."))
  } else {
    message(paste0(nutrient, ": The stratified test and train distributions are more similar."))
  }
  
  return(list(
    Nutrient = nutrient,
    Original = similarity_original,
    Stratified = similarity_list
  ))
}


nutrients <- c("LBC.1", "pH.2", "Ca", "K", "Mg", "Mn", "P", "Zn")  # skip LBC.eq

all_results <- lapply(nutrients, function(nutrient) {
  similarity(get(paste0(nutrient, "_df_train")),
             get(paste0(nutrient, "_df_test")),
             nutrient)
})
#LBC, P and Zn are all stratified
```


#Kriging:
```{r krig setup}

#setting grid as points for kriging
grid<-as.points(covariates)

  #plot(grid)
#set to sf format
grid_sf <- st_as_sf(grid)

grid_sp <- as_Spatial(grid_sf)

soil_points_sf_CID <- st_as_sf(soil_points_CID)

soil_points_sp_CID <- as_Spatial(soil_points_sf_CID)

#variograms:
VarioC <- function(nutrient,data, vgm) {
nut_var<-variogram(nutrient,data = data) 
nut_varfit <- fit.variogram(nut_var, model = vgm(vgm)) 
plot(nut_var, nut_varfit, main = nutrient, sub = "Composite")}

VarioSP <- function(nutrient,data, vgm) {
nut_var<-variogram(nutrient,data = data) 
nut_varfit <- fit.variogram(nut_var, model = vgm(vgm)) 
plot(nut_var, nut_varfit, main = nutrient, sub = "Single Point")}

#kriging function:
Krig <- function(nutrient,data, vgm) {
nut_var_C<-variogram(nutrient,data = data) 
nut_varfit_C <- fit.variogram(nut_var_C, model = vgm(vgm)) 
plot(nut_var_C, nut_varfit_C)
nut_kriged_C<-krige(nutrient,data,grid_sp,model = nut_varfit_C) %>%
  st_as_sf() %>%
  vect()
nut_kriged_raster_C <- rasterize(nut_kriged_C, covariates, field="var1.pred")}


```

##Kriging Composite
```{r Kriging CID}

# #all variograms:
# VarioC(LBC.1~1,soil_points_sp_CID,"Sph")
# VarioC(P~1,soil_points_sp_CID,"Lin")
# VarioC(pH.2~1,soil_points_sp_CID,"Exp")
# VarioC(Ca~1,soil_points_sp_CID,"Sph")
# VarioC(K~1,soil_points_sp_CID,"Sph")
# VarioC(Mg~1,soil_points_sp_CID,"Sph")
# VarioC(Mn~1,soil_points_sp_CID,"Nug")
# VarioC(Zn~1,soil_points_sp_CID,"Nug")

#kriging: 

#LBC:
LBC_krig_C <- Krig(LBC.1~1,soil_points_sp_CID,"Sph") #ehh. Not really a fit. Nugget-esque.
writeRaster(LBC_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/LBC_krig_C.tif", overwrite = TRUE)
#P:
P_krig_C <- Krig(P~1,soil_points_sp_CID,"Lin")
writeRaster(P_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/P_krig_C.tif", overwrite = TRUE)

#pH:
pH_krig_C <- Krig(pH.2~1,soil_points_sp_CID,"Exp")
writeRaster(pH_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/pH_krig_C.tif", overwrite = TRUE)

#Ca:
Ca_krig_C <- Krig(Ca~1,soil_points_sp_CID,"Sph")
writeRaster(Ca_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/Ca_krig_C.tif", overwrite = TRUE)

#K:
K_krig_C <- Krig(K~1,soil_points_sp_CID,"Sph")
writeRaster(K_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/K_krig_C.tif", overwrite = TRUE)

#Mg:
Mg_krig_C <- Krig(Mg~1,soil_points_sp_CID,"Sph")
writeRaster(Mg_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/Mg_krig_C.tif", overwrite = TRUE)
#was nugget, now sph

#Mn:
Mn_krig_C <- Krig(Mn~1,soil_points_sp_CID,"Nug")
writeRaster(Mn_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/Mn_krig_C.tif", overwrite = TRUE)

#Zn
Zn_krig_C <- Krig(Zn~1,soil_points_sp_CID,"Nug")
writeRaster(Zn_krig_C, "..//Local Data- DO NOT PUSH/krig rasters/composite/Zn_krig_C.tif", overwrite = TRUE)


#plotting:
LBC_plot_krig_C <- plot(LBC_krig_C, main = "LBC Kriging Composite") #no fit
P_plot_krig_C <- plot(P_krig_C, main = "P Kriging Composite")
pH_plot_krig_C <- plot(pH_krig_C, main = "Ca Kriging Composite")
Ca_plot_krig_C <- plot(Ca_krig_C, main = "Ca Kriging Composite")
K_plot_krig_C <- plot(K_krig_C, main = "K Kriging Composite")
Mg_plot_krig_C <- plot(Mg_krig_C, main = "Mg Kriging Composite")
Mn_plot_krig_C <- plot(Mn_krig_C, main = "Mn Kriging Composite") #no fit
Zn_plot_krig_C <- plot(Zn_krig_C, main = "Zn Kriging Composite") #no fit

```

##Kriging Single point
```{r Kriging SPID}



soil_points_sf_SPID <- st_as_sf(soil_points_SPID) 
soil_points_sp_SPID <- as_Spatial(soil_points_sf_SPID)

# #all variograms:
VarioSP(LBC.1~1,soil_points_sp_SPID,"Nug")
VarioSP(P~1,soil_points_sp_SPID,"Sph")
VarioSP(pH.2~1,soil_points_sp_SPID,"Exp")
VarioSP(Ca~1,soil_points_sp_SPID,"Sph")
VarioSP(K~1,soil_points_sp_SPID,"Sph")
VarioSP(Mg~1,soil_points_sp_SPID,"Sph")
VarioSP(Mn~1,soil_points_sp_SPID,"Exp")
VarioSP(Zn~1,soil_points_sp_SPID,"Nug")


#LBC:
LBC_krig_SP <- Krig(LBC.1~1,soil_points_sp_SPID,"Nug")
writeRaster(LBC_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/LBC_krig_SP.tif", overwrite = TRUE)

#P:
P_krig_SP <- Krig(P~1,soil_points_sp_SPID,"Sph")
writeRaster(P_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/P_krig_SP.tif", overwrite = TRUE)

#pH:
pH_krig_SP <- Krig(pH.2~1,soil_points_sp_SPID,"Exp")
writeRaster(pH_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/pH_krig_SP.tif", overwrite = TRUE)

#Ca:
Ca_krig_SP <- Krig(Ca~1,soil_points_sp_SPID,"Sph")
writeRaster(Ca_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/Ca_krig_SP.tif", overwrite = TRUE)

#K:
K_krig_SP <- Krig(K~1,soil_points_sp_SPID,"Sph")
writeRaster(K_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/K_krig_SP.tif", overwrite = TRUE)

#Mg:
Mg_krig_SP <- Krig(Mg~1,soil_points_sp_SPID,"Sph") #was nugget, now sph
writeRaster(Mg_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/Mg_krig_SP.tif", overwrite = TRUE)

#Mn:
Mn_krig_SP <- Krig(Mn~1,soil_points_sp_SPID,"Exp")
writeRaster(Mn_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/Mn_krig_SP.tif", overwrite = TRUE)

#Zn
Zn_krig_SP <- Krig(Zn~1,soil_points_sp_SPID,"Nug")
writeRaster(Zn_krig_SP, "..//Local Data- DO NOT PUSH/krig rasters/single point/Zn_krig_SP.tif", overwrite = TRUE)


#plotting:
LBC_plot_krig_SP <- plot(LBC_krig_SP, main = "LBC Kriging Single Point") #no fit
P_plot_krig_SP <- plot(P_krig_SP, main = "P Kriging Single Point")
pH_plot_krig_SP <- plot(pH_krig_SP, main = "Ca Kriging Single Point")
Ca_plot_krig_SP <- plot(Ca_krig_SP, main = "Ca Kriging Single Point")
K_plot_krig_SP <- plot(K_krig_SP, main = "K Kriging Single Point")
Mg_plot_krig_SP <- plot(Mg_krig_SP, main = "Mg Kriging Single Point")
Mn_plot_krig_SP <- plot(Mn_krig_SP, main = "Mn Kriging Single Point") #no fit
Zn_plot_krig_SP <- plot(Zn_krig_SP, main = "Zn Kriging Single Point") #no fit




```


```{r compare krig SP and C}

#plotting all variograms:

VarioSP(LBC.1~1,soil_points_sp_SPID,"Nug")
VarioC(LBC.1~1,soil_points_sp_CID,"Sph")

VarioSP(P~1,soil_points_sp_SPID,"Sph")
VarioC(P~1,soil_points_sp_CID,"Lin")

VarioSP(pH.2~1,soil_points_sp_SPID,"Exp")
VarioC(pH.2~1,soil_points_sp_CID,"Exp")

VarioSP(Ca~1,soil_points_sp_SPID,"Sph")
VarioC(Ca~1,soil_points_sp_CID,"Sph")

VarioSP(K~1,soil_points_sp_SPID,"Sph")
VarioC(K~1,soil_points_sp_CID,"Sph")

VarioSP(Mg~1,soil_points_sp_SPID,"Sph")
VarioC(Mg~1,soil_points_sp_CID,"Exp")

VarioSP(Mn~1,soil_points_sp_SPID,"Exp")
VarioC(Mn~1,soil_points_sp_CID,"Lin")

VarioSP(Zn~1,soil_points_sp_SPID,"Nug")
VarioC(Zn~1,soil_points_sp_CID,"Nug")


```





















##stack
```{r stack}
nutrient_names <- c("LBC.1", "pH.2", "Ca", "K", "Mg", "Mn", "P", "Zn")
#stack every soil variable map together for RF and kriging methods:

#RF:

rf_stack <- list.files("../Local Data- DO NOT PUSH/rf nutrient rasters", full.names = TRUE)%>%
  rast()
names(rf_stack) <- nutrient_names
rf_stack <- terra::mask(rf_stack, border)
plot(rf_stack)


#Kriging:

#composite:
krig_stack_C <-list.files("../Local Data- DO NOT PUSH/krig rasters/composite", full.names = TRUE)%>%
  rast()
names(krig_stack_C) <- nutrient_names
krig_stack_C <- terra::mask(krig_stack_C, border)
plot(krig_stack_C)

#single point:
krig_stack_SP <-list.files("../Local Data- DO NOT PUSH/krig rasters/single point", full.names = TRUE)%>%
  rast()
names(krig_stack_SP) <- nutrient_names
krig_stack_SP <- terra::mask(krig_stack_SP, border)
plot(krig_stack_SP)

```


#Classification

```{r classify P}

#clip:

P_rf_clip_strata <- terra::mask(P_predict_strata, border)
P_krig_clip_strata <- terra::mask(P_krig_SP, border)

#"Low P (0-30 lbs/A)" Apply 140 lbs of P205 per acre
#"Medium P (31-60 lbs/A)" Apply 105 lbs of P205 per acre
#"High P (61-100 lbs/A)" Apply 75 lbs of P205 per acre
#"Very High P (100+ lbs/A)" Apply 0 lbs of P205 per acre



# Define breaks and corresponding labels for Phosphorus (in ppm)
P_classes <- c(0, 15, 30, 50, Inf)  # Breakpoints
P_labels <- c(1, 2, 3, 4)  # Assign numeric labels

# Create classification matrices
P_class_matrix <- cbind(P_classes[-length(P_classes)], P_classes[-1], P_labels)



# Classify P rasters
P_predict_classified <- classify(P_rf_clip_strata, P_class_matrix)
P_kriged_classified <- classify(P_krig_clip_strata, P_class_matrix)


# Assign category labels
P_labels_factor <- c("Low P (0-30 lbs/A)", "Medium P (31-60 lbs/A)", 
                     "High P (61-100 lbs/A)", "Very High P (100+ lbs/A)")


# Convert rasters to categorical factors
levels(P_predict_classified) <- data.frame(ID = 1:4, category = P_labels_factor)
levels(P_kriged_classified) <- data.frame(ID = 1:4, category = P_labels_factor)


par(mfrow = c(2,2))
  #adjusted P
  
  
  # Classify P rasters #P adjusted is just forcing the soil points in
  
  #P_predict_classified_adjust <- classify(P_predict_adjusted_SP, P_class_matrix)


# Assign category labels  for P:

# Convert rasters to categorical factors
levels(P_predict_classified) <- data.frame(ID = 1:4, category = P_labels_factor)
levels(P_kriged_classified) <- data.frame(ID = 1:4, category = P_labels_factor)


par(mfrow = c(2,2))
#RF
plot(P_predict_classified, main = "Classified P (RF Prediction)")
#Kriging
plot(P_kriged_classified, main = "Classified P (Kriging)")


```


```{r Classify K}
#mask:
K_rf_clip_strata <- terra::mask(K_predict, border)
K_krig_clip_strata <- terra::mask(K_krig_C, border)

# Define breaks and corresponding labels for Potassium (in ppm)
K_classes <- c(0, 60, 150, 250, Inf)  # Breakpoints
K_labels <- c(1, 2, 3, 4)  # Assign numeric labels

K_class_matrix <- cbind(K_classes[-length(K_classes)], K_classes[-1], K_labels)

# Classify K rasters
K_predict_classified <- classify(K_rf_clip_strata, K_class_matrix)
K_kriged_classified <- classify(K_krig_clip_strata, K_class_matrix)

K_labels_factor <- c("Low K: (0-60 lbs/A)", "Medium K: (61-150 lbs/A)", "High K (151-250 lbs/A)", "Very High K (250+ lbs/A)")

levels(K_predict_classified) <- data.frame(ID = 1:4, category = K_labels_factor)
levels(K_kriged_classified) <- data.frame(ID = 1:4, category = K_labels_factor)

#custom colors
custom_colors <- viridis(3, option="D")

par(mfrow = c(2,2))
plot(K_predict_classified, main = "Classified K (RF Prediction)", col =custom_colors)

plot(K_kriged_classified, main = "Classified K (Kriging)", col=custom_colors)
```

```{r pH}

# Create a lookup table for lime requirements (lbs/acre)

#BASED ON LIME TABLE C:
lime_table <- tibble(
  pH = c(5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5.0, 4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4.0),
  LBC_100  = c(1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1500, 1500, 1500, 1500, 1500),
  LBC_200  = c(1000, 1000, 1000, 1000, 1000, 1500, 1500, 2000, 2000, 2500, 2500, 3000, 3000, 3000, 3500, 3500, 4000, 4000, 4500, 4500),
  LBC_300  = c(1000, 1000, 1000, 1500, 2000, 2000, 2500, 3000, 3500, 3500, 4000, 4500, 4500, 5000, 5500, 5500, 6000, 6500, 7000, 7000),
  LBC_400  = c(1000, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 5500, 6000, 6500, 7000, 7500, 8000, 8500, 9000, 9500),
  LBC_500  = c(1000, 1500, 2000, 2500, 3000, 3500, 4000, 5000, 5500, 6000, 6500, 7000, 7500, 8500, 9000, 9500, 10000, 10000, 10000, 10000),
  LBC_600  = c(1000, 1500, 2000, 3000, 3500, 4500, 5000, 5500, 6500, 7000, 8000, 8500, 9000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_700  = c(1000, 2000, 2500, 3500, 4000, 5000, 6000, 6500, 7500, 8500, 9000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_800  = c(1000, 2000, 3000, 4000, 5000, 5500, 6500, 7500, 8500, 9500, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_900  = c(1000, 2000, 3500, 4500, 5500, 6500, 7500, 8500, 9500, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_1000 = c(1500, 2500, 3500, 5000, 6000, 7000, 8500, 9500, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_1100 = c(1500, 2500, 4000, 5500, 6500, 8000, 9000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_1200 = c(1500, 3000, 4500, 5500, 7000, 8500, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_1300 = c(1500, 3000, 4500, 6000, 7500, 9000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000),
  LBC_1400 = c(2000, 3500, 5000, 6500, 8500, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000)
)

# Convert lbs/acre to ppm
lime_table[-1] <- lime_table[-1] / 2  # Since 1 ppm ≈ 2 lbs/acre, minus the pH row 

# Function to classify lime requirement
classify_lime <- function(pH, LBC) {
  if (is.na(pH) | is.na(LBC)) return(NA)  # If either value is NA, return NA
  if (pH >= 6) return(0)  # No lime needed if pH is already ≥ 6

  # Find the closest matching pH row
  pH_row <- lime_table %>% filter(pH == max(pH[pH <= pH], na.rm = TRUE)) 
  
  # Find the closest matching LBC column
  LBC_col <- paste0("LBC_", min(max(100, round(LBC, -2)), 1400))  # Rounds to nearest 100
  
  return(as.numeric(pH_row[[LBC_col]]))  # Extract the correct lime value in ppm
}


# Apply to rasters
LBC_pH_stack <- c(LBC.1_predict_strata, pH.2_predict)  # Stack LBC and pH for RF results
LBC_pH_kriged_stack <- c(LBC_krig_SP, pH_krig_SP)  # Stack for kriging results

lime_rf <- app(LBC_pH_stack, fun = function(x) classify_lime(x[2], x[1]))  # x[2] = pH, x[1] = LBC
lime_kriged <- app(LBC_pH_kriged_stack, fun = function(x) classify_lime(x[2], x[1]))

# Rename for clarity
names(lime_rf) <- "Lime_Requirement_RF"
names(lime_kriged) <- "Lime_Requirement_Kriged"

lime_rf_clip_strata <- terra::mask(lime_rf, border)
lime_krig_clip_strata <- terra::mask(lime_kriged, border)


# Plot results
plot(lime_rf_clip_strata, main = "Lime Requirement (RF)")
plot(lime_krig_clip_strata, main = "Lime Requirement (Kriged)")

# Save outputs
writeRaster(lime_rf, "../Local Data- DO NOT PUSH/output/Lime_Requirement_RF.tif", overwrite = TRUE)
writeRaster(lime_kriged, "../Local Data- DO NOT PUSH/output/Lime_Requirement_kriging.tif", overwrite = TRUE)
```


```{r Mg}
classify_Mg_numeric <- function(Mg, pH) {
  if (is.na(Mg) | is.na(pH)) return(NA)  # Handle missing values

  Mg_low <- 30 / 2  # in ppm
  Mg_medium <- 60 / 2  # in ppm

  if (Mg < Mg_low) {
    if (pH < 6) {
      return(1)  # Low Mg - Use Dolomitic Limestone
    } else {
      return(2)  # Low Mg - Apply 25 lbs Mg/Acre
    }
  } else if (Mg < Mg_medium) {
    return(3)  # Medium Mg
  } else {
    return(4)  # High Mg
  }
}



# Define a wrapper function
classify_wrapper <- function(Mg, pH) {
  classify_Mg_numeric(Mg, pH)
}

# RF:
Mg_rf_numeric <- terra::app(c(Mg_predict, pH.2_predict), 
                             function(x) classify_wrapper(x[1], x[2]))

# Kriging:
Mg_kriged_numeric <- terra::app(c(Mg_kriged_raster, pH_krig_C), 
                                 function(x) classify_wrapper(x[1], x[2]))

# Create a lookup table
Mg_categories <- data.frame(
  ID = c(1, 2, 3, 4),
  Mg_Class = c("Low Mg - Use Dolomitic Limestone",
               "Low Mg - Apply 25 lbs Mg/Acre",
               "Medium Mg",
               "High Mg")
)

# Convert to categorical raster
Mg_rf <- terra::as.factor(Mg_rf_numeric)
levels(Mg_rf) <- Mg_categories

Mg_kriged <- terra::as.factor(Mg_kriged_numeric)
levels(Mg_kriged) <- Mg_categories

# Plot results
plot(Mg_rf, main = "Mg Applications (RF)")
plot(Mg_kriged, main = "Mg Application (Kriged)")

```


```{r Mn, eval = FALSE}
# Define Mn classification function
classify_Mn <- function(Mn, pH) {
  if (is.na(Mn) | is.na(pH)) return(NA)  # Handle missing values
  
  if (pH < 5.7 & Mn > 35) return(0)  # No Mn needed if Mn > 35 ppm and pH < 5.7

  # Mn ranges (converted from lbs/acre to ppm)
  Mn_ranges <- c(0, 1.1, 2.3, 3.5, 4.8, 6.0, 7.2, 8.4, 9.6, 10.8, 
                 12.0, 13.3, 14.5, 15.7, 16.9, 18.1, Inf) / 2  # Convert to ppm
  
  pH_thresholds <- c(5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 
                     6.7, 6.8, 6.9, 7.0, 7.1, 7.2)  # Corresponding pH thresholds

  # Find the correct pH threshold based on Mn value
  for (i in seq_along(Mn_ranges)) {
    if (Mn >= Mn_ranges[i] & Mn < Mn_ranges[i + 1]) {
      return(ifelse(pH > pH_thresholds[i], 1, 0))  # Apply Mn if pH is too high
    }
  }

  return(NA)  # Default NA
}

# Wrapper function for classify_Mn
classify_wrapper <- function(vals) {
  classify_Mn(vals[1], vals[2])
}

# Apply classification to raster stacks
Mn_rf_numeric <- terra::app(c(Mn_predict, pH.2_predict), classify_wrapper, cores=4)
Mn_kriged_numeric <- app(c(Mn_kriged_raster, pH_kriged_raster), classify_wrapper, cores=4)

# Create a lookup table for categories
Mn_categories <- data.frame(
  ID = c(0, 1),
  Mn_Class = c("No Mn Needed", "Apply Mn")
)

# Convert numeric values to categories for visualization
Mn_rf <- ratify(Mn_rf_numeric)
levels(Mn_rf) <- Mn_categories

Mn_kriged <- ratify(Mn_kriged_numeric)
levels(Mn_kriged) <- Mn_categories

# Plot results
par(mfrow = c(1, 2))  # Set up plotting area
plot(Mn_rf, main = "Mn Classification (RF Prediction)")
plot(Mn_kriged, main = "Mn Classification (Kriged)")


```


```{r Zn, }
# Define breaks and corresponding labels for Zinc (in ppm)
Zn_classes <- c(0, 1, 4, Inf)  # Breakpoints
Zn_labels <- c(1, 2, 3)  # Assign numeric labels (for low, medium, adequate)

# Create classification matrix
Zn_class_matrix <- cbind(Zn_classes[-length(Zn_classes)], Zn_classes[-1], Zn_labels)

# Classify Zn rasters
Zn_predict_classified <- classify(Zn_predict, Zn_class_matrix)
Zn_kriged_classified <- classify(Zn_kriged_raster, Zn_class_matrix)

# Assign category labels for Zn
Zn_labels_factor <- c("Low Zn (Apply 3 lbs Zn/acre)", 
                      "Medium Zn  (No Zn Needed)", 
                      "Adequate Zn (No Zn Needed)")

# Convert Zn rasters to categorical factors
levels(Zn_predict_classified) <- data.frame(ID = Zn_labels, category = Zn_labels_factor)
levels(Zn_kriged_classified) <- data.frame(ID = Zn_labels, category = Zn_labels_factor)

# Plot results
par(mfrow = c(1, 2))  # Set up plotting area
plot(Zn_predict_classified, main = "Zn Classification (RF Prediction)")
plot(Zn_kriged_classified, main = "Zn Classification (Kriged)")

```







#Condense
```{r Flatten Stacks}
#flatten all soil nutrients together into ONE map per method (RF and kriging)

#need to normalize raster stack first:

rf_stack<-scale(rf_stack)

#PCA RF:
rf_PCA <- spca(rf_stack,
  layers_format = ".tif")

#PCA Krig C:
krig_PCA_C_subset <-  subset(krig_stack_C, c("Mg", "Zn"),  TRUE) #remove nugget rasters

krig_PCA_C <- spca(krig_PCA_C_subset,
  layers_format = ".tif")

#PCA Krig SP:
krig_PCA_SP_subset <-  subset(krig_stack_SP, c("Ca", "Zn"),  TRUE) #remove nugget rasters

krig_PCA_SP <- spca(krig_PCA_SP_subset,
  layers_format = ".tif")

```
```{r PCA method (cluster, reclassify)}

#RF: PCA 1:5?

test_3 <- rf_PCA$pc_layers %>%
  rast() %>%
  select(PC1,PC2,PC3,PC4,PC5) %>%
  k_means(centers = 5)

test_3_zones<-zonal(rf_stack, test_3$lyr1, 'mean')

test_3_poly <- as.polygons(test_3)

test_3_sum <- extract(rf_stack,test_3_poly)

plot(test_3_poly)

test_3_agg <- terra::aggregate(test_3_poly, by = )

plot(test_3_agg)

stats::kmeans(test_3, 5, nstart = 25)





#Krig: PCA 1:4?
  #composite



  #single point

```

























```{r P clustering}


# 1. Aggregate (Optional: Only if you want to reduce resolution)
# Example: Aggregate by a factor of 2 (adjust as needed)
P_rf_agg <- terra::aggregate(P_predict_classified_adjust, fact= 15, fun=modal, expand=TRUE)

# 2. Clump: Identify connected regions with the same value
P_rf_clumped <- raster::clump(raster::raster(P_rf_agg), directions=8)  # Uses 8-direction connectivity

# 3. Sieve: Remove small isolated clumps (e.g., smaller than 5 cells)
P_rf_sieved <- terra::sieve(P_rf_agg, threshold=25)

# 4. Save the cleaned raster
#terra::writeRaster(P_rf_sieved, "P_RF_cleaned.tif", format="GTiff", overwrite=TRUE)

# 5. Plot to check the results
plot(P_rf_sieved, main="Cleaned RF Map (Aggregated, Clumped, and Sieved)")

```

#Clean Maps
```{r Clean Up Maps}
#Clean up into distinct management zones FOR use by farmers

# Resample to lower resolution by aggregating
# by a factor of
factor <- 12
lime_rf_low_res <- aggregate(lime_rf, fact = factor, fun = mean, na.rm = TRUE)

# Convert the low-resolution raster to a matrix for clustering
lime_matrix_low_res <- as.matrix(lime_rf_low_res)

# Reshape the matrix to have a two-column format: pixel index and value
lime_df_low_res <- data.frame(
  pixel_id = seq_len(ncell(lime_rf_low_res)),
  value = as.vector(lime_matrix_low_res)
)

# Remove NAs from the data frame
lime_df_low_res <- na.omit(lime_df_low_res)

# Check the number of unique values
num_unique_values_low_res <- length(unique(lime_df_low_res$value))
cat("Number of unique values in low-res:", num_unique_values_low_res, "\n")

# Set the number of clusters based on unique values, limiting to a maximum of 5
num_clusters_low_res <- min(num_unique_values_low_res, 2)

# Perform K-means clustering on the low-resolution data
set.seed(626)  # Set seed for reproducibility
kmeans_result_low_res <- kmeans(lime_df_low_res$value, centers = num_clusters_low_res)

# Add cluster assignments back to the data frame
lime_df_low_res$cluster <- kmeans_result_low_res$cluster

# Create a new raster for the zones based on low resolution
zone_raster_low_res <- lime_rf_low_res  # Start with the low-res raster
zone_values_low_res <- rep(NA, ncell(zone_raster_low_res))  # Initialize a vector for zone values

# Assign cluster values to the new raster
zone_values_low_res[lime_df_low_res$pixel_id] <- lime_df_low_res$cluster

# Update the zone raster with the cluster values
zone_raster_low_res[] <- zone_values_low_res

# Plot the management zones from the lower resolution raster
plot(zone_raster_low_res, main = "Management Zones for pH (Clustered)", col = terrain.colors(num_clusters_low_res))


```



```{r Clean Up Maps P}


# Step 1: Aggregate while preserving the modal classification
P_rf_agg <- terra::aggregate(P_predict_classified_adjust, fact=12, fun=modal, expand=TRUE)

# Step 2: Set 0 as NoData (mask it out)
P_rf_agg[P_rf_agg == 0] <- NA

# Step 3: Convert to raster format (for clumping)
P_rf_agg_raster <- raster::raster(P_rf_agg)

# Step 4: Clump (group connected cells)
#P_rf_clumped <- raster::clump(P_rf_agg_raster, directions=4)

# Step 5: Sieve (remove small isolated groups)
P_rf_sieved <- terra::sieve(P_rf_agg, threshold=40)

# Step 6: Reclassify values to match labels
classify_P <- matrix(c(1, 1, 2, 2), ncol=2, byrow=TRUE)
P_rf_final <- terra::classify(P_rf_sieved, classify_P)

# Step 7: Assign category labels
P_rf_final <- terra::as.factor(P_rf_final)
levels(P_rf_final) <- data.frame(ID = c(1,2), 
                                 Class = c("Apply 140 lbs of P205 per acre", 
                                           "Apply 105 lbs of P205 per acre"))

# Step 8: Save the cleaned raster
#terra::writeRaster(P_rf_final, "P_RF_cleaned.tif", format="GTiff", overwrite=TRUE)

# Define custom colors using viridis palette
custom_colors <- viridis(4, option="D")[c(1, 2)]  # Ensures 105 lbs is teal

# Step 9: Plot with correct classification
plot(P_rf_final, main="Random Forest Model of P2O5 Recommendations for Corn", 
     col=custom_colors, legend=FALSE)

# Add legend inside the map
legend("topright", legend=c("Apply 140 lbs of P205 per acre", "Apply 105 lbs of P205 per acre"), 
       fill=custom_colors,  inset = c(.07, 0),title="P Recommendation", bty="n", cex=0.5)

```


```{r P clustering}



# 1. Aggregate (Optional: Only if you want to reduce resolution)
# Example: Aggregate by a factor of 2 (adjust as needed)
P_rf_agg <- terra::aggregate(P_predict_classified_adjust, fact= 15, fun=modal, expand=TRUE)

# 2. Clump: Identify connected regions with the same value
P_rf_clumped <- raster::clump(raster::raster(P_rf_agg), directions=8)  # Uses 8-direction connectivity

# 3. Sieve: Remove small isolated clumps (e.g., smaller than 5 cells)
P_rf_sieved <- terra::sieve(P_rf_agg, threshold=25)

# 4. Save the cleaned raster
#terra::writeRaster(P_rf_sieved, "P_RF_cleaned.tif", format="GTiff", overwrite=TRUE)

# 5. Plot to check the results
plot(P_rf_sieved, main="Cleaned RF Map (Aggregated, Clumped, and Sieved)")

```




```{r Compare Maps}




# Define custom viridis colors for classification (same across all maps)
custom_colors <- viridis(4, option = "D")

# Assign category labels for P
P_labels_factor <- c("Apply 140 lbs of P205 per acre", "Apply 105 lbs of P205 per acre",
                     "Apply 75 lbs of P205 per acre", "Apply 0 lbs of P205 per acre")

# Assign category labels for K
K_labels_factor <- c("Apply 180 lbs of K2O per acre", "Apply 140 lbs of K2O per acre", 
                     "Apply 120 lbs of K2O per acre", "Apply 0 lbs of K2O per acre")

# Create separate plots for each raster with legends outside

# Plot RF classified P

plot(P_rf_final, main = "Random Forest Model of P2O5 Recommendations for Corn", col=custom_colors, legend=FALSE)
legend("topright", inset = c(.07, 0), legend=P_labels_factor, fill=custom_colors, 
       title="P Recommendation", bty="n", cex=0.5)  # Smaller text 



# Plot RF classified K
plot(K_predict_classified, main = "Random Forest Model of K2O Recommendations for Corn", col=custom_colors, legend=FALSE)
legend("topright", inset = c(.07, 0), legend=K_labels_factor, fill=custom_colors, 
       title="K Recommendation", bty="n", cex=0.5)  # Smaller text

# Plot Kriged classified P
plot(P_kriged_classified, main = "Kriging Model of P2O5 Recommendations for Corn", col=custom_colors, legend=FALSE)
legend("topright", inset = c(.07, 0), legend=P_labels_factor, fill=custom_colors, 
       title="P Recommendation", bty="n", cex=0.5)  # Smaller text

# Plot Kriged classified K
plot(K_kriged_classified, main = "Kriging Model of K2O Recommendations for Corn)", col=custom_colors, legend=FALSE)
legend("topright", inset = c(.07, 0), legend=K_labels_factor, fill=custom_colors, 
       title="K Recommendation", bty="n", cex=0.5)  # Smaller text

```




```{r export classified P RF }
# Export the raster as a .tif file
terra::writeRaster(P_predict_classified_adjust, 
                   filename = "../Mapping/Output/GIS maps/P_RF_map.tif", 
                   overwrite = TRUE)










png("../Mapping/Output/RF_P_MAP_FINAL.png", width = 10, height = 7, units = "in", res = 300)

# Define custom colors using viridis palette
custom_colors <- viridis(4, option="D")[c(1, 2)]  # Ensures 105 lbs is teal

# Step 9: Plot with correct classification
plot(P_rf_final, main="Random Forest Model of P2O5 Recommendations for Corn", 
     col=custom_colors, legend=FALSE)

# Add legend inside the map
legend("topright", legend=c("Apply 140 lbs of P205 per acre", "Apply 105 lbs of P205 per acre"), 
       fill=custom_colors,  inset = c(.07, 0.01),title="P Recommendation", bty="n", cex=0.8)
dev.off





#krig
png("../Mapping/Output/KRIG_P_MAP_FINAL.png", width = 10, height = 7, units = "in", res = 300)

# Plot Kriged classified P
plot(P_kriged_classified, main = "Kriging Model of P2O5 Recommendations for Corn", col=custom_colors, legend=FALSE)
legend("topright", inset = c(.07, .01), legend=P_labels_factor, fill=custom_colors, 
       title="P Recommendation", bty="n", cex=0.8)  # Smaller text
dev.off
```



```{r Compare Maps}
#results
```





